---
name: Build Self-Host

on:
  workflow_dispatch:

jobs:
  stub:
    name: Stub
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Stub
        run: echo "Stub"
