---
name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release Version"
        required: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-20.04
    outputs:
      branch-name: ${{ steps.branch.outputs.branch-name }}
    steps:
      # - name: Branch check
      #   run: |
      #     if [[ "$GITHUB_REF" != "refs/heads/rc" ]] && [[ "$GITHUB_REF" != "refs/heads/hotfix" ]]; then
      #       echo "==================================="
      #       echo "[!] Can only release from the 'rc' or 'hotfix' branches"
      #       echo "==================================="
      #       exit 1
      #     fi

      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Get Latest Self-Host Version
        id: get-self-host
        uses: bitwarden/gh-actions/get-release-version@664c8899c95490c65dac0df11519d24ed8419c85
        with:
          repository: bitwarden/self-host

      # - name: Check Release Version
      #   env:
      #     RELEASE_VERSION: ${{ github.event.inputs.release_version }}
      #     PREVIOUS_RELEASE_VERSION: ${{ steps.get-self-host.outputs.version }}
      #   run: |
      #     if [ "$RELEASE_VERSION" == "$PREVIOUS_RELEASE_VERSION" ]; then
      #       echo "[!] Already released v$RELEASE_VERSION. Please bump version to continue"
      #       exit 1
      #     fi

      - name: Get branch name
        id: branch
        run: |
          BRANCH_NAME=$(basename ${{ github.ref }})
          echo "::set-output name=branch-name::$BRANCH_NAME"


  release:
    name: Create GitHub Release
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: ${{ needs.setup.outputs.branch-name }}

      # - name: Create release
      #   uses: ncipollo/release-action@95215a3cb6e6a1908b3c44e00b4fdb15548b1e09
      #   with:
      #     artifacts: 'bitwarden.sh,
      #                 run.sh,
      #                 bitwarden.ps1,
      #                 run.ps1,
      #                 version.json'
      #     commit: ${{ github.sha }}
      #     tag: "v${{ github.event.inputs.release_version }}"
      #     name: "Version ${{ github.event.inputs.release_version }}"
      #     body: "<insert release notes here>"
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     draft: true

  release-version:
    name: Upload version.json
    runs-on: ubuntu-20.04
    needs:
     - setup
     - release
    steps:
      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: ${{ needs.setup.outputs.branch-name }}

      - name: Login to Azure
        uses: Azure/login@ec3c14589bd3e9312b3cc8c41e6860e258df9010
        with:
          creds: ${{ secrets.AZURE_PROD_KV_CREDENTIALS }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: Azure/get-keyvault-secrets@b5c723b9ac7870c022b8c35befe620b7009b336f
        with:
          keyvault: "bitwarden-prod-kv"
          secrets: "aws-selfhost-version-access-id, aws-selfhost-version-access-key"

      - name: Upload version.json to S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.retrieve-secrets.outputs.aws-selfhost-version-access-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.retrieve-secrets.outputs.aws-selfhost-version-access-key }}
          AWS_DEFAULT_REGION: 'us-west-2'
          AWS_S3_BUCKET_NAME: 's3://public-s3-bitwarden-selfhost-version-artifact'
        run: |
          aws s3 cp version.json $AWS_S3_BUCKET_NAME \
          --acl "public-read" \
          --quiet
