---
name: Update Links

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release Tag"
        required: true

jobs:
  update-links:
    name: Update Links
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Azure - Prod Subscription
        uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
        with:
          creds: ${{ secrets.AZURE_PROD_KV_CREDENTIALS }}

      - name: Retrieve secrets
        id: retrieve-secrets
        env:
          KEYVAULT: bitwarden-prod-kv
          SECRETS: |
            rebrandly-apikey
        run: |
          for i in ${SECRETS//,/ }
          do
            VALUE=$(az keyvault secret show --vault-name $KEYVAULT --name $i --query value --output tsv)
            echo "::add-mask::$VALUE"
            echo "::set-output name=$i::$VALUE"
          done

      - name: Set tag name
        id: tag-name
        run: |
          if [ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]; then
            echo "::set-output name=value::${{ github.event.inputs.release_tag }}"
          else
            echo "::set-output name=value::$GITHUB_REF_NAME"
          fi

      - name: Update Bitwarden Script PowerShell Link
        uses: bitwarden/gh-actions/update-rebrandly-link@340a677ffb0c53e50ca67cd2c12044cd7f7fc725
        with:
          apikey: ${{ steps.retrieve-secrets.outputs.rebrandly-apikey }}
          domain: "go.btwrdn.co"
          slashtag: "bw-ps"
          destination: "https://github.com/bitwarden/self-host/releases/download/${{ steps.tag-name.outputs.value }}/bitwarden.ps1"

      - name: Update Run Script PowerShell Link
        uses: bitwarden/gh-actions/update-rebrandly-link@340a677ffb0c53e50ca67cd2c12044cd7f7fc725
        with:
          apikey: ${{ steps.retrieve-secrets.outputs.rebrandly-apikey }}
          domain: "go.btwrdn.co"
          slashtag: "bw-ps-run"
          destination: "https://github.com/bitwarden/self-host/releases/download/${{ steps.tag-name.outputs.value }}/run.ps1"

      - name: Update Bitwarden Script Shell Link
        uses: bitwarden/gh-actions/update-rebrandly-link@340a677ffb0c53e50ca67cd2c12044cd7f7fc725
        with:
          apikey: ${{ steps.retrieve-secrets.outputs.rebrandly-apikey }}
          domain: "go.btwrdn.co"
          slashtag: "bw-sh"
          destination: "https://github.com/bitwarden/self-host/releases/download/${{ steps.tag-name.outputs.value }}/bitwarden.sh"

      - name: Update Run Script Shell Link
        uses: bitwarden/gh-actions/update-rebrandly-link@340a677ffb0c53e50ca67cd2c12044cd7f7fc725
        with:
          apikey: ${{ steps.retrieve-secrets.outputs.rebrandly-apikey }}
          domain: "go.btwrdn.co"
          slashtag: "bw-sh-run"
          destination: "https://github.com/bitwarden/self-host/releases/download/${{ steps.tag-name.outputs.value }}/run.sh"
